/**
 * Screen-by-screen study engine. Renders one question/screen into a
 * container element at a time and drives progression via callbacks. Kept
 * framework-free and auditable: every screen a participant can see is a
 * function here, not generated by a black-box templating layer.
 */
import { OAH_QUESTIONS, STUDY_QUESTIONS, OVERALL_RATINGS, type OahQuestion } from "../questions/oah-source";
import { getGuidedQuestion, ORIENTATION_STEP, GUIDED_OVERRIDES } from "../questions/guided";
import { getSiteById, type Arm, type ParticipantState } from "../study/assign";

export type Answers = Record<string, string | string[]>;

export interface SiteResult {
  siteId: string;
  answers: Answers; // question id -> code or codes[]
  overallRating: string;
  msStarted: number;
  msFinished: number;
}

const NOT_SURE = "NOT_SURE";

function el(html: string): HTMLElement {
  const div = document.createElement("div");
  div.innerHTML = html.trim();
  return div.firstElementChild as HTMLElement;
}

function refImages(paths: string[] | undefined, baseDir: string): string {
  if (!paths || paths.length === 0) return "";
  const imgs = paths
    .map((p) => {
      const src = p.startsWith("urban/")
        ? `/reference-photos/${p}`
        : `/reference-photos/${baseDir}/${p}`;
      return `<img class="ref-photo" src="${src}" alt="reference" loading="lazy" onerror="this.style.display='none'" />`;
    })
    .join("");
  return `<div class="ref-row">${imgs}</div>`;
}

/** Renders a single/yesno/multi question. Calls onAnswer(value) once submitted. */
function renderQuestion(
  container: HTMLElement,
  question: OahQuestion,
  arm: Arm,
  optionOrderForId: string[] | undefined,
  progressPct: number,
  onAnswer: (value: string | string[]) => void,
  extraTop?: string
) {
  const baseDir = arm === "baseline" ? "oah-app" : "oah-app"; // both share the same OAH illustration set; guided adds extras separately
  const info = question.info ? `<p class="muted">${question.info}</p>` : "";
  const preNote =
    arm === "guided" && GUIDED_OVERRIDES[question.id]?.preNote
      ? `<div class="note">${GUIDED_OVERRIDES[question.id]!.preNote}</div>`
      : "";

  let bodyHtml = "";
  if (question.kind === "yesno") {
    const opts = ["Yes", "No", ...(question.hasNotSure ? ["I am not sure"] : [])];
    bodyHtml = `<div class="options">${opts
      .map((o) => `<label class="opt" data-val="${o}"><input type="radio" name="q" value="${o}" /> ${o}</label>`)
      .join("")}</div>`;
  } else if (question.kind === "single") {
    const codes = optionOrderForId ?? (question.options ?? []).map((o) => o.code);
    const byCode = new Map((question.options ?? []).map((o) => [o.code, o.label]));
    const opts = codes.map((c) => `<label class="opt" data-val="${c}"><input type="radio" name="q" value="${c}" /> ${byCode.get(c)}</label>`);
    if (question.hasNotSure)
      opts.push(`<label class="opt" data-val="${NOT_SURE}"><input type="radio" name="q" value="${NOT_SURE}" /> I am not sure</label>`);
    bodyHtml = `<div class="options">${opts.join("")}</div>`;
  } else if (question.kind === "multi") {
    const codes = optionOrderForId ?? (question.options ?? []).map((o) => o.code);
    const byCode = new Map((question.options ?? []).map((o) => [o.code, o.label]));
    const opts = codes.map((c) => `<label class="opt" data-val="${c}"><input type="checkbox" name="q" value="${c}" /> ${byCode.get(c)}</label>`);
    bodyHtml = `<div class="options">${opts.join("")}</div>
      <p class="muted">Select all that apply, or none.</p>`;
  } else if (question.kind === "number") {
    bodyHtml = `<input type="number" step="0.1" min="0" id="numAns" placeholder="e.g. 0.5" />`;
  }

  container.innerHTML = "";
  container.appendChild(
    el(`
    <div class="card">
      <div class="progress"><div style="width:${progressPct}%"></div></div>
      ${extraTop ?? ""}
      <h2>${question.label}</h2>
      <p>${question.prompt}</p>
      ${info}
      ${preNote}
      ${refImages(question.referenceImages, baseDir)}
      ${bodyHtml}
      <div class="row">
        <span></span>
        <button id="nextBtn" disabled>Continue</button>
      </div>
    </div>
  `)
  );

  const nextBtn = container.querySelector<HTMLButtonElement>("#nextBtn")!;

  if (question.kind === "number") {
    const input = container.querySelector<HTMLInputElement>("#numAns")!;
    input.addEventListener("input", () => {
      nextBtn.disabled = input.value.trim() === "";
    });
    nextBtn.addEventListener("click", () => onAnswer(input.value.trim()));
    return;
  }

  const optEls = Array.from(container.querySelectorAll<HTMLElement>(".opt"));
  const isMulti = question.kind === "multi";

  const updateSelectedClass = () => {
    optEls.forEach((o) => {
      const input = o.querySelector("input") as HTMLInputElement;
      o.classList.toggle("selected", input.checked);
    });
  };

  optEls.forEach((o) => {
    o.addEventListener("click", (e) => {
      if ((e.target as HTMLElement).tagName !== "INPUT") {
        const input = o.querySelector("input") as HTMLInputElement;
        if (input.type === "checkbox") input.checked = !input.checked;
        else input.checked = true;
      }
      updateSelectedClass();
      const checked = optEls.filter((x) => (x.querySelector("input") as HTMLInputElement).checked);
      nextBtn.disabled = !isMulti && checked.length === 0;
      if (isMulti) nextBtn.disabled = false; // allow "none selected" as a valid multi answer
    });
  });

  nextBtn.addEventListener("click", () => {
    const checked = optEls.filter((x) => (x.querySelector("input") as HTMLInputElement).checked);
    if (isMulti) {
      onAnswer(checked.map((x) => x.dataset.val!));
    } else {
      onAnswer(checked[0]?.dataset.val ?? NOT_SURE);
    }
  });
}

/** Runs a decomposed yes/no sequence (guided arm only) and resolves to a single code. */
function renderDecomposedSequence(
  container: HTMLElement,
  question: OahQuestion,
  steps: { prompt: string; yesCode: string | null }[],
  progressPct: number,
  onAnswer: (code: string) => void
) {
  let stepIdx = 0;
  const allCodes = new Set((question.options ?? []).map((o) => o.code));
  const usedCodes = new Set(steps.map((s) => s.yesCode).filter(Boolean) as string[]);
  const remainder = [...allCodes].find((c) => !usedCodes.has(c));

  const showStep = () => {
    if (stepIdx >= steps.length) {
      onAnswer(remainder ?? steps[steps.length - 1]?.yesCode ?? NOT_SURE);
      return;
    }
    const step = steps[stepIdx];
    container.innerHTML = "";
    container.appendChild(
      el(`
      <div class="card">
        <div class="progress"><div style="width:${progressPct}%"></div></div>
        <span class="badge">${question.label} — step ${stepIdx + 1} of ${steps.length}</span>
        <p style="font-size:1.05rem;font-weight:600;">${step.prompt}</p>
        ${refImages(question.referenceImages, "oah-app")}
        <div class="options">
          <label class="opt" data-val="yes"><input type="radio" name="s" value="yes" /> Yes</label>
          <label class="opt" data-val="no"><input type="radio" name="s" value="no" /> No</label>
          <label class="opt" data-val="unsure"><input type="radio" name="s" value="unsure" /> I'm not sure</label>
        </div>
        <div class="row"><span></span><button id="nextBtn" disabled>Continue</button></div>
      </div>
    `)
    );
    const optEls = Array.from(container.querySelectorAll<HTMLElement>(".opt"));
    const nextBtn = container.querySelector<HTMLButtonElement>("#nextBtn")!;
    optEls.forEach((o) => {
      o.addEventListener("click", () => {
        optEls.forEach((x) => x.classList.remove("selected"));
        o.classList.add("selected");
        (o.querySelector("input") as HTMLInputElement).checked = true;
        nextBtn.disabled = false;
      });
    });
    nextBtn.addEventListener("click", () => {
      const val = optEls.find((x) => (x.querySelector("input") as HTMLInputElement).checked)?.dataset.val;
      if (val === "unsure") {
        onAnswer(NOT_SURE);
      } else if (val === "yes" && step.yesCode) {
        onAnswer(step.yesCode);
      } else {
        stepIdx++;
        showStep();
      }
    });
  };
  showStep();
}

function renderOrientation(container: HTMLElement, onContinue: () => void) {
  container.innerHTML = "";
  container.appendChild(
    el(`
    <div class="card">
      <span class="badge">Before you start</span>
      <h2>${ORIENTATION_STEP.title}</h2>
      <p>${ORIENTATION_STEP.body}</p>
      <img class="ref-photo" src="/reference-photos/${ORIENTATION_STEP.image}" alt="orientation" onerror="this.style.display='none'" />
      <div class="row"><span></span><button id="nextBtn">Got it</button></div>
    </div>
  `)
  );
  container.querySelector("#nextBtn")!.addEventListener("click", onContinue);
}

function renderSitePhoto(container: HTMLElement, siteId: string, index: number, total: number, onContinue: () => void) {
  const site = getSiteById(siteId)!;
  container.innerHTML = "";
  container.appendChild(
    el(`
    <div class="card">
      <div class="progress"><div style="width:${(index / total) * 100}%"></div></div>
      <span class="badge">Site ${index + 1} of ${total}</span>
      <h2>Look at this stream</h2>
      <p class="muted">${site.city} — take a moment before answering.</p>
      <img class="site-photo" src="${site.image}" alt="stream site" />
      <div class="row"><span></span><button id="nextBtn">Start assessing</button></div>
    </div>
  `)
  );
  container.querySelector("#nextBtn")!.addEventListener("click", onContinue);
}

function renderEvidenceRecap(container: HTMLElement, siteId: string, answers: Answers, progressPct: number, onContinue: () => void) {
  const site = getSiteById(siteId)!;
  const rows = STUDY_QUESTIONS.map((q) => {
    const v = answers[q.id];
    if (v === undefined) return "";
    const label = Array.isArray(v) ? (v.length ? v.join(", ") : "none") : v === NOT_SURE ? "not sure" : v;
    return `<div class="recap-item"><span>${q.label}</span><span>${label}</span></div>`;
  }).join("");

  container.innerHTML = "";
  container.appendChild(
    el(`
    <div class="card">
      <div class="progress"><div style="width:${progressPct}%"></div></div>
      <h2>Before you rate ${site.city}</h2>
      <p class="muted">Here's what you reported for this site:</p>
      ${rows}
      <div class="row"><span></span><button id="nextBtn">Now give the overall rating</button></div>
    </div>
  `)
  );
  container.querySelector("#nextBtn")!.addEventListener("click", onContinue);
}

function renderOverallRating(container: HTMLElement, progressPct: number, onAnswer: (code: string) => void) {
  container.innerHTML = "";
  const cards = OVERALL_RATINGS.map(
    (r) => `
    <div class="rating-card" data-val="${r.code}">
      <strong>${r.label}</strong>
      <p class="muted" style="margin:4px 0 0;">${r.description}</p>
    </div>`
  ).join("");
  container.appendChild(
    el(`
    <div class="card">
      <div class="progress"><div style="width:${progressPct}%"></div></div>
      <h2>Overall assessment</h2>
      <p>Provide an overall assessment of the stream ecosystem health.</p>
      ${cards}
      <div class="row"><span></span><button id="nextBtn" disabled>Continue</button></div>
    </div>
  `)
  );
  const cardEls = Array.from(container.querySelectorAll<HTMLElement>(".rating-card"));
  const nextBtn = container.querySelector<HTMLButtonElement>("#nextBtn")!;
  cardEls.forEach((c) => {
    c.addEventListener("click", () => {
      cardEls.forEach((x) => x.classList.remove("selected"));
      c.classList.add("selected");
      nextBtn.disabled = false;
    });
  });
  nextBtn.addEventListener("click", () => {
    const val = cardEls.find((c) => c.classList.contains("selected"))!.dataset.val!;
    onAnswer(val);
  });
}

/**
 * Runs the full sequence of study questions for one site, then the
 * evidence recap (guided arm only) and overall rating. Calls onDone with
 * the collected SiteResult.
 */
export function runSite(
  container: HTMLElement,
  participant: ParticipantState,
  siteId: string,
  siteIndex: number,
  totalSites: number,
  onDone: (result: SiteResult) => void
) {
  const arm = participant.arm;
  const msStarted = Date.now();
  const answers: Answers = {};
  let qi = 0;

  const totalScreens = STUDY_QUESTIONS.length + 2; // + photo + rating
  const progressFor = (step: number) => Math.round(((siteIndex + step / totalScreens) / totalSites) * 100);

  const askNext = () => {
    if (qi >= STUDY_QUESTIONS.length) {
      const finish = () => {
        renderOverallRating(container, progressFor(STUDY_QUESTIONS.length + 1), (rating) => {
          onDone({ siteId, answers, overallRating: rating, msStarted, msFinished: Date.now() });
        });
      };
      if (arm === "guided") {
        renderEvidenceRecap(container, siteId, answers, progressFor(STUDY_QUESTIONS.length), finish);
      } else {
        finish();
      }
      return;
    }

    const baseQ = STUDY_QUESTIONS[qi];
    const q = arm === "guided" ? getGuidedQuestion(baseQ.id) : baseQ;
    const decomposed = arm === "guided" ? GUIDED_OVERRIDES[baseQ.id]?.decomposed : undefined;

    const advance = (val: string | string[]) => {
      answers[baseQ.id] = val;
      // Guided special-case: draining_pipes gate feeds sewage_discharge.
      if (arm === "guided" && baseQ.id === "draining_pipes" && val === "No") {
        answers["sewage_discharge"] = "No";
      }
      qi++;
      askNext();
    };

    if (decomposed) {
      renderDecomposedSequence(container, q, decomposed.steps, progressFor(qi), advance);
    } else {
      renderQuestion(container, q, arm, participant.optionOrder[baseQ.id], progressFor(qi), advance);
    }
  };

  renderSitePhoto(container, siteId, siteIndex, totalSites, askNext);
}

export function showOrientationIfNeeded(container: HTMLElement, participant: ParticipantState, onContinue: () => void) {
  if (participant.arm === "guided") {
    renderOrientation(container, onContinue);
  } else {
    onContinue();
  }
}

export { OAH_QUESTIONS };
